### ISSUE TITLE
请教一下作者，这个版本的LVI代码需要更改xacro文件吗？

### ISSUE THREAD

**Issue by fuxinsen** [YJZLuckyBoy/LVI-SAM-Simple#1]
看了作者的博客和仓库的readme文件，有一事不解：适配自己的传感器数据时需要同步调整LVI-SAM-Simple-master/launch/include/config/robot.urdf.xacro里的内容吗，我看博客里的LIO部分提到了而readme里没提，谢谢！

**Comment by YJZLuckyBoy** [comment]
> 看了作者的博客和仓库的readme文件，有一事不解：适配自己的传感器数据时需要同步调整LVI-SAM-Simple-master/launch/include/config/robot.urdf.xacro里的内容吗，我看博客里的LIO部分提到了而readme里没提，谢谢！

抱歉回复不及时，urdf主要是配置融合gps时的一些参数，如果不融合gps不需要配置的，后面我会发布一个不依赖于robot-localization功能包的融合gps版本

**Comment by fuxinsen** [comment]
> 抱歉回复不及时，urdf主要是配置融合gps时的一些参数，如果不融合gps不需要配置的，后面我会发布一个不依赖于robot-localization功能包的融合gps版本

感谢！！！
